// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EmojiBody: typeof import('./src/components/emoji-picker/src/EmojiBody.vue')['default']
    EmojiFooter: typeof import('./src/components/emoji-picker/src/EmojiFooter.vue')['default']
    EmojiHeader: typeof import('./src/components/emoji-picker/src/EmojiHeader.vue')['default']
    EmojiPicker: typeof import('./src/components/emoji-picker/src/EmojiPicker.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
